
    drop table if exists admin_audit_logs cascade constraints;
    drop table if exists award cascade constraints;
    drop table if exists bega_diary cascade constraints;
    drop table if exists bega_diary_photo_urls cascade constraints;
    drop table if exists chat_messages cascade constraints;
    drop table if exists check_in_records cascade constraints;
    drop table if exists cheer_battle_log cascade constraints;
    drop table if exists cheer_battle_votes cascade constraints;
    drop table if exists cheer_comment cascade constraints;
    drop table if exists cheer_comment_like cascade constraints;
    drop table if exists cheer_post cascade constraints;
    drop table if exists cheer_post_bookmark cascade constraints;
    drop table if exists cheer_post_like cascade constraints;
    drop table if exists cheer_post_reports cascade constraints;
    drop table if exists cheer_post_repost cascade constraints;
    drop table if exists game cascade constraints;
    drop table if exists game_inning_scores cascade constraints;
    drop table if exists game_metadata cascade constraints;
    drop table if exists game_summary cascade constraints;
    drop table if exists notifications cascade constraints;
    drop table if exists parties cascade constraints;
    drop table if exists party_applications cascade constraints;
    drop table if exists password_reset_tokens cascade constraints;
    drop table if exists places cascade constraints;
    drop table if exists player_movements cascade constraints;
    drop table if exists post_images cascade constraints;
    drop table if exists predictions cascade constraints;
    drop table if exists ranking_predictions cascade constraints;
    drop table if exists refresh_tokens cascade constraints;
    drop table if exists stadiums cascade constraints;
    drop table if exists team_franchises cascade constraints;
    drop table if exists team_history cascade constraints;
    drop table if exists team_profiles cascade constraints;
    drop table if exists teams cascade constraints;
    drop table if exists user_block cascade constraints;
    drop table if exists user_follow cascade constraints;
    drop table if exists user_providers cascade constraints;
    drop table if exists users cascade constraints;
    drop table if exists vote_final_results cascade constraints;

    create table admin_audit_logs (
        admin_id number(19,0) not null,
        created_at timestamp(6) not null,
        id number(19,0) generated by default as identity,
        target_user_id number(19,0) not null,
        new_value varchar2(100 char),
        old_value varchar2(100 char),
        description varchar2(500 char),
        action varchar2(20 char) check (action in ('DELETE_MATE','DELETE_POST','DELETE_USER','DEMOTE_TO_USER','PROMOTE_TO_ADMIN')),
        primary key (id)
    );

    create table award (
        award_year number(10,0) not null,
        id number(19,0) generated by default as identity,
        award_type varchar2(255 char) not null,
        player_name varchar2(255 char) not null,
        position varchar2(255 char),
        primary key (id)
    );

    create table bega_diary (
        diarydate date not null unique,
        createdat timestamp(6) not null,
        game_id number(19,0) not null,
        id number(19,0) generated by default as identity,
        updatedat timestamp(6) not null,
        user_id number(19,0) not null,
        block varchar2(50 char),
        seat_number varchar2(50 char),
        seat_row varchar2(50 char),
        section varchar2(50 char),
        memo varchar2(500 char),
        stadium varchar2(255 char) not null,
        team varchar2(255 char) not null,
        mood varchar2(20 char) check (mood in ('ANGRY','BEST','FULL','HAPPY','WORST')),
        type varchar2(20 char) check (type in ('ATTENDED','SCHEDULED')),
        winning varchar2(20 char) check (winning in ('DRAW','LOSE','WIN')),
        primary key (id)
    );

    create table bega_diary_photo_urls (
        bega_diary_id number(19,0) not null,
        photo_urls varchar2(255 char)
    );

    create table chat_messages (
        created_at timestamp(6) with time zone not null,
        id number(19,0) generated by default as identity,
        party_id number(19,0) not null,
        sender_id number(19,0) not null,
        sender_name varchar2(50 char) not null,
        message varchar2(1000 char) not null,
        primary key (id)
    );

    create table check_in_records (
        checked_in_at timestamp(6) not null,
        id number(19,0) generated by default as identity,
        party_id number(19,0) not null,
        user_id number(19,0) not null,
        location varchar2(100 char) not null,
        primary key (id)
    );

    create table cheer_battle_log (
        id number(19,0) generated by default as identity,
        voted_at timestamp(6) with time zone not null,
        game_id varchar2(255 char) not null,
        team_id varchar2(255 char) not null,
        user_email varchar2(255 char) not null,
        primary key (id)
    );

    create table cheer_battle_votes (
        vote_count number(10,0),
        game_id varchar2(255 char) not null,
        team_id varchar2(255 char) not null,
        primary key (game_id, team_id)
    );

    create table cheer_comment (
        like_count number(10,0) not null,
        author_id number(19,0) not null,
        created_at timestamp(6) with time zone not null,
        id number(19,0) generated by default as identity,
        parent_comment_id number(19,0),
        post_id number(19,0) not null,
        updated_at timestamp(6) with time zone not null,
        content clob not null,
        primary key (id)
    );

    create table cheer_comment_like (
        comment_id number(19,0) not null,
        createdat timestamp(6) with time zone not null,
        user_id number(19,0) not null,
        primary key (comment_id, user_id)
    );

    create table cheer_post (
        commentcount number(10,0) not null,
        deleted number(1,0) not null,
        likecount number(10,0) not null,
        repostcount number(10,0) not null,
        views number(10,0) not null,
        author_id number(19,0) not null,
        createdat timestamp(6) with time zone not null,
        id number(19,0) generated by default as identity,
        repost_of_id number(19,0),
        updatedat timestamp(6) with time zone not null,
        title varchar2(100 char) not null,
        content clob,
        team_id varchar2(255 char) not null,
        posttype varchar2(20 char) check (posttype in ('NORMAL','NOTICE')),
        repost_type varchar2(20 char) check (repost_type in ('QUOTE','SIMPLE')),
        primary key (id)
    );

    create table cheer_post_bookmark (
        created_at timestamp(6) with time zone not null,
        post_id number(19,0) not null,
        user_id number(19,0) not null,
        primary key (post_id, user_id)
    );

    create table cheer_post_like (
        createdat timestamp(6) with time zone not null,
        post_id number(19,0) not null,
        user_id number(19,0) not null,
        primary key (post_id, user_id)
    );

    create table cheer_post_reports (
        createdat timestamp(6) not null,
        id number(19,0) generated by default as identity,
        post_id number(19,0) not null,
        reporter_id number(19,0) not null,
        description clob,
        reason varchar2(50 char) check (reason in ('ABUSIVE_LANGUAGE','ADVERTISEMENT','INAPPROPRIATE_CONTENT','OTHER','SPAM')),
        primary key (id)
    );

    create table cheer_post_repost (
        created_at timestamp(6),
        post_id number(19,0) not null,
        user_id number(19,0) not null,
        primary key (post_id, user_id)
    );

    create table game (
        away_score number(10,0),
        game_date date,
        home_score number(10,0),
        is_dummy number(1,0),
        season_id number(10,0),
        winning_score number(10,0),
        id number(19,0) generated by default as identity,
        away_team varchar2(20 char),
        game_id varchar2(20 char) not null unique,
        game_status varchar2(20 char),
        home_team varchar2(20 char),
        winning_team varchar2(20 char),
        away_pitcher varchar2(30 char),
        home_pitcher varchar2(30 char),
        stadium varchar2(50 char),
        stadium_id varchar2(50 char),
        primary key (id)
    );

    create table game_inning_scores (
        id number(10,0) generated by default as identity,
        inning number(10,0) not null,
        is_extra number(1,0),
        runs number(10,0),
        team_code varchar2(10 char),
        team_side varchar2(10 char) not null,
        game_id varchar2(20 char) not null,
        primary key (id)
    );

    create table game_metadata (
        attendance number(10,0),
        end_time timestamp(6),
        game_time_minutes number(10,0),
        start_time timestamp(6),
        game_id varchar2(20 char) not null,
        stadium_code varchar2(20 char),
        stadium_name varchar2(50 char),
        weather varchar2(50 char),
        source_payload clob,
        primary key (game_id)
    );

    create table game_summary (
        id number(10,0) generated by default as identity,
        player_id number(10,0),
        created_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone,
        game_id varchar2(20 char) not null,
        player_name varchar2(50 char),
        summary_type varchar2(50 char),
        detail_text clob,
        primary key (id)
    );

    create table notifications (
        is_read number(1,0) not null,
        createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
        id number(19,0) generated by default as identity,
        related_id number(19,0),
        user_id number(19,0) not null,
        title varchar2(200 char) not null,
        message varchar2(500 char) not null,
        type varchar2(50 char) check (type in ('APPLICATION_APPROVED','APPLICATION_RECEIVED','APPLICATION_REJECTED','COMMENT_REPLY','FOLLOWING_NEW_POST','NEW_FOLLOWER','POST_COMMENT','POST_LIKE','POST_REPOST')),
        primary key (id)
    );

    create table parties (
        current_participants number(10,0) not null,
        game_date date not null,
        game_time timestamp(6) not null,
        host_rating float(53) not null,
        max_participants number(10,0) not null,
        price number(10,0),
        ticket_verified number(1,0) not null,
        ticketprice number(10,0),
        created_at timestamp(6) with time zone not null,
        hostid number(19,0) not null,
        id number(19,0) generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        away_team varchar2(20 char) not null,
        home_team varchar2(20 char) not null,
        host_favorite_team varchar2(20 char),
        team_id varchar2(20 char) not null,
        host_name varchar2(50 char) not null,
        section varchar2(50 char) not null,
        stadium varchar2(100 char) not null,
        ticket_image_url varchar2(500 char),
        description varchar2(1000 char) not null,
        host_profile_image_url varchar2(2048 char),
        host_badge varchar2(20 char) check (host_badge in ('NEW','TRUSTED','VERIFIED')),
        status varchar2(20 char) check (status in ('CHECKED_IN','COMPLETED','FAILED','MATCHED','PENDING','SELLING','SOLD')),
        primary key (id)
    );

    create table party_applications (
        applicant_rating float(53) not null,
        deposit_amount number(10,0) not null,
        is_approved number(1,0) not null,
        is_paid number(1,0) not null,
        is_rejected number(1,0) not null,
        applicantid number(19,0) not null,
        approved_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        id number(19,0) generated by default as identity,
        partyid number(19,0) not null,
        rejected_at timestamp(6) with time zone,
        applicant_name varchar2(50 char) not null,
        message varchar2(500 char) not null,
        applicant_badge varchar2(20 char) check (applicant_badge in ('NEW','TRUSTED','VERIFIED')),
        payment_type varchar2(20 char) check (payment_type in ('DEPOSIT','FULL')),
        primary key (id)
    );

    create table password_reset_tokens (
        used number(1,0) not null,
        expiry_date timestamp(6) not null,
        id number(19,0) generated by default as identity,
        user_id number(19,0) not null,
        token varchar2(255 char) not null unique,
        primary key (id)
    );

    create table places (
        lat float(53) not null,
        lng float(53) not null,
        rating number(2,1),
        created_at timestamp(6),
        id number(19,0) generated by default as identity,
        updated_at timestamp(6),
        phone varchar2(20 char),
        category varchar2(50 char) not null,
        close_time varchar2(50 char),
        open_time varchar2(50 char),
        name varchar2(100 char) not null,
        address varchar2(255 char),
        description clob,
        stadium_id varchar2(255 char) not null,
        primary key (id)
    );

    create table player_movements (
        date_mv date not null,
        created_at timestamp(6) not null,
        id number(19,0) generated by default as identity,
        updated_at timestamp(6) not null,
        team_code varchar2(20 char) not null,
        section varchar2(50 char) not null,
        player_name varchar2(100 char) not null,
        remarks clob,
        primary key (id)
    );

    create table post_images (
        is_thumbnail number(1,0) not null,
        bytes number(19,0) not null,
        created_at timestamp(6) with time zone not null,
        id number(19,0) generated by default as identity,
        post_id number(19,0) not null,
        mime_type varchar2(100 char) not null,
        storage_path varchar2(255 char) not null,
        primary key (id)
    );

    create table predictions (
        created_at timestamp(6),
        id number(19,0) generated by default as identity,
        user_id number(19,0),
        game_id varchar2(255 char) not null,
        voted_team varchar2(255 char) not null,
        primary key (id)
    );

    create table ranking_predictions (
        season_year number(10,0),
        created_at timestamp(6),
        id number(19,0) generated by default as identity,
        user_id varchar2(255 char),
        prediction_data clob check (prediction_data is json),
        primary key (id)
    );

    create table refresh_tokens (
        expirydate timestamp(6),
        id number(19,0) generated by default as identity,
        email varchar2(255 char),
        token varchar2(255 char),
        primary key (id)
    );

    create table stadiums (
        capacity number(10,0),
        center_fence_m float(53),
        fence_height_m float(53),
        homerun_park_factor float(53),
        lat float(53),
        left_fence_m float(53),
        lng float(53),
        open_year number(10,0),
        seating_capacity number(10,0),
        created_at timestamp(6),
        updated_at timestamp(6),
        address varchar2(255 char),
        bullpen_type varchar2(255 char),
        city varchar2(255 char),
        notes clob,
        phone varchar2(255 char),
        stadium_id varchar2(255 char) not null,
        stadium_name varchar2(255 char),
        team varchar2(255 char),
        turf_type varchar2(255 char),
        primary key (stadium_id)
    );

    create table team_franchises (
        id number(10,0) generated by default as identity,
        created_at timestamp(6),
        updated_at timestamp(6),
        current_code varchar2(10 char) not null,
        original_code varchar2(10 char) not null unique,
        name varchar2(50 char) not null,
        web_url varchar2(255 char),
        metadata_json clob check (metadata_json is json),
        primary key (id)
    );

    create table team_history (
        franchise_id number(10,0) not null,
        id number(10,0) generated by default as identity,
        ranking number(10,0),
        season number(10,0) not null,
        created_at timestamp(6),
        updated_at timestamp(6),
        team_code varchar2(10 char) not null,
        city varchar2(30 char),
        color varchar2(50 char),
        stadium varchar2(50 char),
        team_name varchar2(50 char) not null,
        logo_url varchar2(255 char),
        primary key (id),
        unique (season, team_code)
    );

    create table team_profiles (
        profile varchar2(255 char) not null,
        team_id varchar2(255 char) not null
    );

    create table teams (
        founded_year number(10,0),
        franchise_id number(10,0),
        is_active number(1,0),
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        city varchar2(30 char) not null,
        stadium_name varchar2(50 char),
        color varchar2(255 char),
        team_id varchar2(255 char) not null,
        team_name varchar2(255 char),
        team_short_name varchar2(255 char),
        aliases clob check (aliases is json),
        primary key (team_id)
    );

    create table user_block (
        blocked_id number(19,0) not null,
        blocker_id number(19,0) not null,
        created_at timestamp(6) with time zone not null,
        primary key (blocked_id, blocker_id)
    );

    create table user_follow (
        notify_new_posts number(1,0) not null,
        created_at timestamp(6) with time zone not null,
        follower_id number(19,0) not null,
        following_id number(19,0) not null,
        primary key (follower_id, following_id)
    );

    create table user_providers (
        connected_at timestamp(6) with time zone,
        id number(19,0) generated by default as identity,
        user_id number(19,0) not null,
        provider varchar2(20 char) not null,
        providerid varchar2(255 char) not null,
        primary key (id),
        unique (provider, providerid),
        unique (user_id, provider)
    );

    create table users (
        cheer_points number(10,0) not null,
        last_bonus_date date,
        private_account number(1,0) not null,
        created_at timestamp(6) with time zone not null,
        id number(19,0) generated by default as identity,
        last_login_date timestamp(6) with time zone,
        handle varchar2(15 char) not null unique,
        unique_id varchar2(255 char) not null unique,
        bio varchar2(500 char),
        profile_image_url varchar2(512 char),
        email varchar2(255 char) not null unique,
        favorite_team varchar2(255 char),
        name varchar2(255 char) not null,
        password varchar2(255 char),
        provider varchar2(255 char),
        providerid varchar2(255 char),
        role varchar2(255 char) not null,
        primary key (id)
    );

    create table vote_final_results (
        final_votes_a number(10,0) not null,
        final_votes_b number(10,0) not null,
        updated_at timestamp(6),
        final_winner varchar2(255 char),
        game_id varchar2(255 char) not null,
        primary key (game_id)
    );

    create index idx_cheer_post_type_created_at
       on cheer_post (posttype, createdat desc);

    create index idx_cheer_team_post_type_created_at
       on cheer_post (team_id, posttype, createdat desc);

    create index idx_game_date
       on game (game_date);

    create index idx_season_id
       on game (season_id);

    create index idx_game_teams
       on game (home_team, away_team);

    alter table bega_diary
       add constraint FKjgbnwssi3o44cc3xuiu7iilym
       foreign key (game_id)
       references game;

    alter table bega_diary
       add constraint FKg1h0v4lncbxntejxcoxynwcr7
       foreign key (user_id)
       references users;

    alter table bega_diary_photo_urls
       add constraint FKng93taewk5q3tcmj99rrgkfq9
       foreign key (bega_diary_id)
       references bega_diary;

    alter table cheer_comment
       add constraint FKimunpwn6835rdapdtdy90xdsl
       foreign key (author_id)
       references users;

    alter table cheer_comment
       add constraint FKfrj0t2cun4wm4ar5iuj1d8n5w
       foreign key (parent_comment_id)
       references cheer_comment;

    alter table cheer_comment
       add constraint FKave5wa7kq1dg3xpqd38oenwu2
       foreign key (post_id)
       references cheer_post;

    alter table cheer_comment_like
       add constraint FKo4rgxkhwgo4pijakq9mafx08m
       foreign key (comment_id)
       references cheer_comment;

    alter table cheer_comment_like
       add constraint FKrb7hmp5gkdff1wn4bdo84hq8
       foreign key (user_id)
       references users;

    alter table cheer_post
       add constraint FK586irvtl4r29n7fjso6v5fvu9
       foreign key (author_id)
       references users;

    alter table cheer_post
       add constraint FKqi9a7nww871u6mkbyeiw7sk6x
       foreign key (repost_of_id)
       references cheer_post;

    alter table cheer_post
       add constraint FKquua05jk136x5ysv260f2m5kk
       foreign key (team_id)
       references teams;

    alter table cheer_post_bookmark
       add constraint FK7bhbl8fh2v49w0jnydr7fe72a
       foreign key (post_id)
       references cheer_post;

    alter table cheer_post_bookmark
       add constraint FK5w3lvsg31uuocry6bi4ogx049
       foreign key (user_id)
       references users;

    alter table cheer_post_like
       add constraint FKpakax2loslyidlq81kopq5d12
       foreign key (post_id)
       references cheer_post;

    alter table cheer_post_like
       add constraint FKfq6t1o31vqba5nrgo4h0096pk
       foreign key (user_id)
       references users;

    alter table cheer_post_reports
       add constraint FKs8qt6ssyt76uyt08dvjntqng8
       foreign key (post_id)
       references cheer_post;

    alter table cheer_post_reports
       add constraint FKoys2122v99kyt76nu5koo9utq
       foreign key (reporter_id)
       references users;

    alter table cheer_post_repost
       add constraint FKkc3w966p2spjjx2bi03hgcpu1
       foreign key (post_id)
       references cheer_post;

    alter table cheer_post_repost
       add constraint FKihyj3rhkfio41woo559m83qfj
       foreign key (user_id)
       references users;

    alter table password_reset_tokens
       add constraint FKk3ndxg5xp6v7wd4gjyusp15gq
       foreign key (user_id)
       references users;

    alter table places
       add constraint FKla6f2666a3bp09k7hbtdhemv4
       foreign key (stadium_id)
       references stadiums;

    alter table post_images
       add constraint FKamk1smy84a3fyyvtbg08x8fs3
       foreign key (post_id)
       references cheer_post;

    alter table team_history
       add constraint FKf746g97ruqx8394w5mkd70w44
       foreign key (franchise_id)
       references team_franchises;

    alter table team_profiles
       add constraint FKsxqfinb14py8b1ijir5kqikk8
       foreign key (team_id)
       references teams;

    alter table teams
       add constraint FK77dhnkvhla152qwjc5yylhn7t
       foreign key (franchise_id)
       references team_franchises;

    alter table user_block
       add constraint FKisl1bda7awqgr4u3t6fkjgeyi
       foreign key (blocked_id)
       references users;

    alter table user_block
       add constraint FKcq98e7xnnyx515oob3gi6p4ig
       foreign key (blocker_id)
       references users;

    alter table user_follow
       add constraint FKi9gqdjcgtclgypxp2krye61n7
       foreign key (follower_id)
       references users;

    alter table user_follow
       add constraint FK474orxbed564dk0mvggvt4xon
       foreign key (following_id)
       references users;

    alter table user_providers
       add constraint FKjn43qct6quty65mmawu66aesk
       foreign key (user_id)
       references users;

    alter table users
       add constraint FKsoshv1kx35h84j3nsijydk7yv
       foreign key (favorite_team)
       references teams;

    -- Add missing KBO tables
    drop table if exists kbo_seasons cascade constraints;
    drop table if exists player_basic cascade constraints;
    drop table if exists player_season_batting cascade constraints;
    drop table if exists player_season_pitching cascade constraints;
    drop table if exists game_batting_stats cascade constraints;
    drop table if exists game_pitching_stats cascade constraints;

    create table kbo_seasons (
        season_id number(10,0) primary key,
        season_year number(10,0) not null,
        league_type_code number(10,0) not null,
        league_type_name varchar2(255 char) not null,
        start_date date,
        end_date date,
        created_at timestamp(6) with time zone default current_timestamp,
        updated_at timestamp(6) with time zone default current_timestamp
    );

    create table player_basic (
        player_id number(10,0) primary key,
        name varchar2(255 char) not null,
        uniform_no varchar2(255 char),
        team varchar2(255 char),
        position varchar2(255 char),
        birth_date varchar2(255 char),
        birth_date_date date,
        height_cm number(10,0),
        weight_kg number(10,0),
        career varchar2(255 char),
        status varchar2(255 char),
        staff_role varchar2(255 char),
        status_source varchar2(255 char)
    );

    create table player_season_batting (
        id number(10,0) generated by default as identity primary key,
        player_id number(10,0) not null,
        season number(10,0) not null,
        league varchar2(255 char) default 'REGULAR' not null,
        league_level varchar2(255 char) default 'KBO1' not null,
        data_source varchar2(255 char) default 'ROLLUP' not null,
        team_code varchar2(255 char),
        games number(10,0),
        plate_appearances number(10,0),
        at_bats number(10,0),
        runs number(10,0),
        hits number(10,0),
        doubles number(10,0),
        triples number(10,0),
        home_runs number(10,0),
        rbi number(10,0),
        walks number(10,0),
        intentional_walks number(10,0),
        hbp number(10,0),
        strikeouts number(10,0),
        stolen_bases number(10,0),
        caught_stealing_number number(10,0),
        sacrifice_hits number(10,0),
        sacrifice_flies number(10,0),
        gdp number(10,0),
        avg float(53),
        obp float(53),
        slg float(53),
        ops float(53),
        iso float(53),
        babip float(53),
        extra_stats clob check (extra_stats is json),
        created_at timestamp(6) with time zone default current_timestamp,
        updated_at timestamp(6) with time zone default current_timestamp,
        season_id number(10,0)
    );

    create table player_season_pitching (
        id number(10,0) generated by default as identity primary key,
        player_id number(10,0) not null,
        season number(10,0) not null,
        league varchar2(255 char) default 'REGULAR' not null,
        league_level varchar2(255 char) default 'KBO1' not null,
        data_source varchar2(255 char) default 'CRAWLER' not null,
        team_code varchar2(255 char),
        games number(10,0),
        games_started number(10,0),
        wins number(10,0),
        losses number(10,0),
        saves number(10,0),
        holds number(10,0),
        innings_pitched float(53),
        hits_allowed number(10,0),
        runs_allowed number(10,0),
        earned_runs number(10,0),
        home_runs_allowed number(10,0),
        walks_allowed number(10,0),
        intentional_walks number(10,0),
        hit_batters number(10,0),
        strikeouts number(10,0),
        wild_pitches number(10,0),
        balks number(10,0),
        era float(53),
        whip float(53),
        fip float(53),
        k_per_nine float(53),
        bb_per_nine float(53),
        kbb float(53),
        complete_games number(10,0),
        shutouts number(10,0),
        quality_starts number(10,0),
        blown_saves number(10,0),
        tbf number(10,0),
        np number(10,0),
        avg_against float(53),
        doubles_allowed number(10,0),
        triples_allowed number(10,0),
        sacrifices_allowed number(10,0),
        sacrifice_flies_allowed number(10,0),
        extra_stats clob check (extra_stats is json),
        created_at timestamp(6) with time zone default current_timestamp,
        updated_at timestamp(6) with time zone default current_timestamp,
        season_id number(10,0),
        innings_outs number(10,0),
        innings_display number
    );

    create table game_batting_stats (
        id number(10,0) generated by default as identity primary key,
        game_id varchar2(255 char) not null,
        team_side varchar2(255 char) not null,
        team_code varchar2(255 char),
        player_id number(10,0),
        player_name varchar2(255 char) not null,
        batting_order number(10,0),
        is_starter number(1,0) default 0,
        appearance_seq number(10,0) not null,
        position varchar2(255 char),
        plate_appearances number(10,0) default 0,
        at_bats number(10,0) default 0,
        runs number(10,0) default 0,
        hits number(10,0) default 0,
        doubles number(10,0) default 0,
        triples number(10,0) default 0,
        home_runs number(10,0) default 0,
        rbi number(10,0) default 0,
        walks number(10,0) default 0,
        intentional_walks number(10,0) default 0,
        hbp number(10,0) default 0,
        strikeouts number(10,0) default 0,
        stolen_bases number(10,0) default 0,
        caught_stealing number(10,0) default 0,
        sacrifice_hits number(10,0) default 0,
        sacrifice_flies number(10,0) default 0,
        gdp number(10,0) default 0,
        avg float(53),
        obp float(53),
        slg float(53),
        ops float(53),
        iso float(53),
        babip float(53),
        extra_stats clob check (extra_stats is json),
        created_at timestamp(6) with time zone default current_timestamp,
        updated_at timestamp(6) with time zone default current_timestamp
    );

    create table game_pitching_stats (
        id number(10,0) generated by default as identity primary key,
        game_id varchar2(255 char) not null,
        team_side varchar2(255 char) not null,
        team_code varchar2(255 char),
        player_id number(10,0),
        player_name varchar2(255 char) not null,
        is_starting number(1,0) default 0,
        appearance_seq number(10,0) not null,
        innings_outs number(10,0) default 0,
        innings_pitched number,
        batters_faced number(10,0) default 0,
        pitches number(10,0) default 0,
        hits_allowed number(10,0) default 0,
        runs_allowed number(10,0) default 0,
        earned_runs number(10,0) default 0,
        home_runs_allowed number(10,0) default 0,
        walks_allowed number(10,0) default 0,
        strikeouts number(10,0) default 0,
        hit_batters number(10,0) default 0,
        wild_pitches number(10,0) default 0,
        balks number(10,0) default 0,
        wins number(10,0) default 0,
        losses number(10,0) default 0,
        saves number(10,0) default 0,
        holds number(10,0) default 0,
        decision varchar2(255 char),
        era float(53),
        whip float(53),
        k_per_nine float(53),
        bb_per_nine float(53),
        kbb float(53),
        extra_stats clob check (extra_stats is json),
        created_at timestamp(6) with time zone default current_timestamp,
        updated_at timestamp(6) with time zone default current_timestamp
    );
