-- ============================================================
-- V1: 경기장 참조 데이터 Oracle(ADB) 베이스라인
--
-- 범위: **stadiums, places 2개뿐이다.**
--
-- ── 왜 야구 테이블이 여기 없나 (2026-08-17 정정) ──────────
-- 야구 테이블(game, teams, player_movements, awards 등)의 소유자는 이 저장소가
-- 아니라 크롤러 프로젝트다.
--
--   https://github.com/rkdansdlf/KBO_playwright
--   migrations/oracle/README.md:
--     "Oracle uses the SQLAlchemy ORM metadata as the initial schema baseline"
--     python3 -m src.cli.apply_oracle_migrations
--
-- 크롤러가 ADB 에 Base.metadata.create_all() 로 스키마를 만든다. 우리가 같은
-- 테이블을 Flyway 로 또 선언하면 **하나의 DB 를 두고 두 개의 스키마 정의가
-- 싸운다.** 그래서 크롤러 영역은 만들지 않고 읽기만 한다.
--
-- 소유권 판정은 하드코딩이 아니라 계약에서 끌어온다 --
-- contracts/baseball-schema/*_schema.csv 에 있으면 크롤러 소유다.
-- 생성기(scripts/gen_oracle_baseball_ddl.py)가 --skip-crawler-tables 로 걸러낸다.
-- 크롤러가 테이블을 추가하면 자동으로 제외되므로 목록이 낡지 않는다.
--
-- stadiums / places 는 계약에 없다. 경기장 참조 데이터이고 StadiumAdminService 가
-- places 를 직접 쓰기 때문에 우리 소유다.
--
-- ── 출처 ──────────────────────────────────────────────────
-- 운영 PostgreSQL(pgvector-db/bega_backend)의 실제 스키마를
-- scripts/gen_oracle_baseball_ddl.py 로 변환해 생성했다. 손으로 고치지 말고 재생성할 것.
--
-- ── 타입 매핑 ─────────────────────────────────────────────
--   character varying -> VARCHAR2(n CHAR)   double precision -> BINARY_DOUBLE
--   numeric           -> NUMBER(p,s)        timestamp        -> TIMESTAMP
--   nextval 기본값     -> GENERATED BY DEFAULT ON NULL AS IDENTITY
--
-- ⚠️ 미검증 (2026-08-17). ADB 접속이 ACL 로 막혀 실제 적용 확인을 못 했다.
-- ============================================================

DECLARE
    -- 이미 있으면 넘어간다(ORA-00955). 그 외 오류는 그대로 올린다.
    PROCEDURE ddl(p_sql VARCHAR2) IS
        e_already_exists EXCEPTION;
        PRAGMA EXCEPTION_INIT(e_already_exists, -955);
    BEGIN
        EXECUTE IMMEDIATE p_sql;
    EXCEPTION
        WHEN e_already_exists THEN NULL;
    END;
BEGIN

    -- ══ 테이블 ═══════════════════════════════════════════════
    ddl(q'[
        CREATE TABLE stadiums (
            stadium_id           VARCHAR2(255 CHAR) NOT NULL,
            stadium_name         VARCHAR2(255 CHAR),
            city                 VARCHAR2(255 CHAR),
            open_year            NUMBER(10),
            capacity             NUMBER(10),
            seating_capacity     NUMBER(10),
            left_fence_m         BINARY_DOUBLE,
            center_fence_m       BINARY_DOUBLE,
            fence_height_m       BINARY_DOUBLE,
            turf_type            VARCHAR2(255 CHAR),
            bullpen_type         VARCHAR2(255 CHAR),
            homerun_park_factor  BINARY_DOUBLE,
            notes                VARCHAR2(255 CHAR),
            lat                  BINARY_DOUBLE,
            lng                  BINARY_DOUBLE,
            address              VARCHAR2(255 CHAR),
            phone                VARCHAR2(255 CHAR),
            team                 VARCHAR2(255 CHAR),
            created_at           TIMESTAMP,
            updated_at           TIMESTAMP
        )
    ]');

    ddl(q'[
        CREATE TABLE places (
            id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
            stadium_id   VARCHAR2(255 CHAR) NOT NULL,
            category     VARCHAR2(50 CHAR) NOT NULL,
            name         VARCHAR2(100 CHAR) NOT NULL,
            description  VARCHAR2(255 CHAR),
            lat          BINARY_DOUBLE NOT NULL,
            lng          BINARY_DOUBLE NOT NULL,
            address      VARCHAR2(255 CHAR),
            phone        VARCHAR2(20 CHAR),
            rating       NUMBER(2,1),
            open_time    VARCHAR2(50 CHAR),
            close_time   VARCHAR2(50 CHAR),
            created_at   TIMESTAMP,
            updated_at   TIMESTAMP
        )
    ]');


    -- ══ 기본키 / 외래키 / 인덱스 ══════════════════════════════
    ddl('ALTER TABLE stadiums ADD CONSTRAINT pk_stadiums PRIMARY KEY (stadium_id)');
    ddl('ALTER TABLE places ADD CONSTRAINT pk_places PRIMARY KEY (id)');
    ddl('ALTER TABLE places ADD CONSTRAINT fk_places_stadium '
        || 'FOREIGN KEY (stadium_id) REFERENCES stadiums (stadium_id)');
    ddl('CREATE INDEX idx_places_stadium_id ON places (stadium_id)');
    ddl('CREATE INDEX idx_places_stadium_category ON places (stadium_id, category)');
END;
/
