DECLARE
    v_ticket_verified NUMBER := 0;
    v_ticket_verified_at NUMBER := 0;
    v_table_exists NUMBER := 0;
    v_index_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_ticket_verified
      FROM user_tab_cols
     WHERE table_name = 'BEGA_DIARY'
       AND column_name = 'TICKET_VERIFIED';

    IF v_ticket_verified = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE bega_diary ADD (ticket_verified NUMBER(1) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*)
      INTO v_ticket_verified_at
      FROM user_tab_cols
     WHERE table_name = 'BEGA_DIARY'
       AND column_name = 'TICKET_VERIFIED_AT';

    IF v_ticket_verified_at = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE bega_diary ADD (ticket_verified_at TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*)
      INTO v_table_exists
      FROM user_tables
     WHERE table_name = 'SEAT_VIEW_PHOTO';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE seat_view_photo (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                diary_id NUMBER(19) NOT NULL,
                user_id NUMBER(19) NOT NULL,
                storage_path VARCHAR2(2048) NOT NULL,
                source_type VARCHAR2(32) NOT NULL,
                ai_suggested_label VARCHAR2(32),
                ai_confidence NUMBER(10, 6),
                ai_reason VARCHAR2(1000),
                user_selected NUMBER(1) DEFAULT 0 NOT NULL,
                moderation_status VARCHAR2(32),
                admin_label VARCHAR2(32),
                admin_memo VARCHAR2(1000),
                reviewed_by NUMBER(19),
                reviewed_at TIMESTAMP(6),
                reward_granted NUMBER(1) DEFAULT 0 NOT NULL,
                createdat TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                updatedat TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT pk_seat_view_photo PRIMARY KEY (id),
                CONSTRAINT fk_seat_view_photo_diary FOREIGN KEY (diary_id)
                    REFERENCES bega_diary (id) ON DELETE CASCADE
            )';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'IDX_SEAT_VIEW_PHOTO_DIARY_ID';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_seat_view_photo_diary_id ON seat_view_photo (diary_id)';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'IDX_SEAT_VIEW_PHOTO_PUBLIC';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_seat_view_photo_public ON seat_view_photo (moderation_status, admin_label, user_selected)';
    END IF;
END;
/
