-- V116: Add account security events, trusted devices, and soft delete metadata (Oracle)

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_cols
     WHERE table_name = 'USERS'
       AND column_name = 'PENDING_DELETION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE users ADD (pending_deletion NUMBER(1) DEFAULT 0 NOT NULL)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_cols
     WHERE table_name = 'USERS'
       AND column_name = 'DELETION_REQUESTED_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE users ADD (deletion_requested_at TIMESTAMP NULL)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_cols
     WHERE table_name = 'USERS'
       AND column_name = 'DELETION_SCHEDULED_FOR';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE users ADD (deletion_scheduled_for TIMESTAMP NULL)';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'TRUSTED_DEVICES';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE trusted_devices (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                fingerprint VARCHAR2(128 CHAR) NOT NULL,
                device_label VARCHAR2(255 CHAR) NOT NULL,
                device_type VARCHAR2(32 CHAR) NOT NULL,
                browser VARCHAR2(64 CHAR) NOT NULL,
                os VARCHAR2(64 CHAR) NOT NULL,
                first_seen_at TIMESTAMP NOT NULL,
                last_seen_at TIMESTAMP NOT NULL,
                last_login_at TIMESTAMP NOT NULL,
                last_ip VARCHAR2(64 CHAR),
                revoked_at TIMESTAMP NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE trusted_devices
            ADD CONSTRAINT fk_trusted_devices_user
            FOREIGN KEY (user_id) REFERENCES users(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE UNIQUE INDEX uq_trusted_devices_user_fingerprint
            ON trusted_devices(user_id, fingerprint)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX ix_trusted_devices_user_last_seen
            ON trusted_devices(user_id, last_seen_at DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'ACCOUNT_SECURITY_EVENTS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE account_security_events (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                occurred_at TIMESTAMP NOT NULL,
                event_type VARCHAR2(64 CHAR) NOT NULL,
                device_label VARCHAR2(255 CHAR),
                device_type VARCHAR2(32 CHAR),
                browser VARCHAR2(64 CHAR),
                os VARCHAR2(64 CHAR),
                ip VARCHAR2(64 CHAR),
                message VARCHAR2(500 CHAR) NOT NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE account_security_events
            ADD CONSTRAINT fk_account_security_events_user
            FOREIGN KEY (user_id) REFERENCES users(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX ix_account_security_events_user_occurred
            ON account_security_events(user_id, occurred_at DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'ACCOUNT_DELETION_TOKENS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE account_deletion_tokens (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                token VARCHAR2(128 CHAR) NOT NULL,
                expiry_date TIMESTAMP NOT NULL,
                used NUMBER(1) DEFAULT 0 NOT NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE account_deletion_tokens
            ADD CONSTRAINT fk_account_deletion_tokens_user
            FOREIGN KEY (user_id) REFERENCES users(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE UNIQUE INDEX uq_account_deletion_tokens_token
            ON account_deletion_tokens(token)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX ix_account_deletion_tokens_user_id
            ON account_deletion_tokens(user_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
