DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'CLIENT_ERROR_EVENTS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE client_error_events (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                event_id VARCHAR2(64 CHAR) NOT NULL,
                bucket VARCHAR2(20 CHAR) NOT NULL,
                source VARCHAR2(40 CHAR) NOT NULL,
                message VARCHAR2(1000 CHAR) NOT NULL,
                stack_trace CLOB NULL,
                component_stack CLOB NULL,
                route VARCHAR2(500 CHAR) NOT NULL,
                normalized_route VARCHAR2(500 CHAR) NOT NULL,
                status_code NUMBER(10) NULL,
                status_group VARCHAR2(8 CHAR) DEFAULT ''none'' NOT NULL,
                response_code VARCHAR2(64 CHAR) NULL,
                method VARCHAR2(16 CHAR) NULL,
                endpoint VARCHAR2(500 CHAR) NULL,
                normalized_endpoint VARCHAR2(500 CHAR) NULL,
                occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                session_id VARCHAR2(128 CHAR) NULL,
                user_id NUMBER(19) NULL,
                fingerprint VARCHAR2(64 CHAR) NOT NULL,
                feedback_count NUMBER(10) DEFAULT 0 NOT NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        ALTER TABLE client_error_events
            ADD CONSTRAINT uq_client_error_events_event_id UNIQUE (event_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_events_occurred_at
            ON client_error_events(occurred_at DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_events_bucket_occurred_at
            ON client_error_events(bucket, occurred_at DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_events_fingerprint
            ON client_error_events(fingerprint)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_events_normalized_route
            ON client_error_events(normalized_route)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'CLIENT_ERROR_FEEDBACK';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE client_error_feedback (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                event_id VARCHAR2(64 CHAR) NOT NULL,
                "COMMENT" CLOB NOT NULL,
                action_taken VARCHAR2(64 CHAR) NOT NULL,
                route VARCHAR2(500 CHAR) NOT NULL,
                occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_feedback_event_id
            ON client_error_feedback(event_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_feedback_occurred_at
            ON client_error_feedback(occurred_at DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'CLIENT_ERROR_ALERT_NOTIFICATIONS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE client_error_alert_notifications (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                fingerprint VARCHAR2(64 CHAR) NOT NULL,
                bucket VARCHAR2(20 CHAR) NOT NULL,
                source VARCHAR2(40 CHAR) NOT NULL,
                route VARCHAR2(500 CHAR) NOT NULL,
                status_group VARCHAR2(8 CHAR) DEFAULT ''none'' NOT NULL,
                observed_count NUMBER(19) NOT NULL,
                threshold_count NUMBER(10) NOT NULL,
                window_minutes NUMBER(10) NOT NULL,
                latest_event_id VARCHAR2(64 CHAR) NULL,
                latest_message VARCHAR2(1000 CHAR) NULL,
                latest_occurred_at TIMESTAMP NULL,
                notified_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                delivery_status VARCHAR2(20 CHAR) NOT NULL,
                failure_reason VARCHAR2(1000 CHAR) NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_alert_notifications_fingerprint
            ON client_error_alert_notifications(fingerprint)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE '
        CREATE INDEX idx_client_error_alert_notifications_notified_at
            ON client_error_alert_notifications(notified_at DESC)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
