-- V127: Create AI chat session/message/favorite tables for authenticated chatbot persistence (Oracle)

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'AI_CHAT_SESSION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE ai_chat_session (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                title VARCHAR2(120 CHAR) NOT NULL,
                message_count NUMBER(10) DEFAULT 0 NOT NULL,
                last_message_preview VARCHAR2(500 CHAR),
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                last_message_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'AI_CHAT_MESSAGE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE ai_chat_message (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                session_id NUMBER NOT NULL,
                role VARCHAR2(16 CHAR) NOT NULL,
                status VARCHAR2(20 CHAR) NOT NULL,
                content CLOB NOT NULL,
                verified NUMBER(1),
                cached NUMBER(1),
                intent VARCHAR2(100 CHAR),
                strategy VARCHAR2(100 CHAR),
                finish_reason VARCHAR2(50 CHAR),
                cancelled NUMBER(1) DEFAULT 0 NOT NULL,
                error_code VARCHAR2(100 CHAR),
                planner_mode VARCHAR2(50 CHAR),
                planner_cache_hit NUMBER(1),
                tool_execution_mode VARCHAR2(50 CHAR),
                fallback_reason VARCHAR2(100 CHAR),
                metadata_json CLOB,
                citations_json CLOB,
                tool_calls_json CLOB,
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'AI_CHAT_FAVORITE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE ai_chat_favorite (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                message_id NUMBER NOT NULL,
                created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE ai_chat_session
            ADD CONSTRAINT fk_ai_chat_session_user
            FOREIGN KEY (user_id) REFERENCES users(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE ai_chat_message
            ADD CONSTRAINT fk_ai_chat_msg_session
            FOREIGN KEY (session_id) REFERENCES ai_chat_session(id) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE ai_chat_favorite
            ADD CONSTRAINT fk_ai_chat_fav_user
            FOREIGN KEY (user_id) REFERENCES users(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE ai_chat_favorite
            ADD CONSTRAINT fk_ai_chat_fav_msg
            FOREIGN KEY (message_id) REFERENCES ai_chat_message(id) ON DELETE CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE ai_chat_favorite
            ADD CONSTRAINT uq_ai_chat_fav_usr_msg
            UNIQUE (user_id, message_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 AND SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_ai_chat_session_user_last ON ai_chat_session(user_id, last_message_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_ai_chat_msg_session_created ON ai_chat_message(session_id, created_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_ai_chat_fav_user_created ON ai_chat_favorite(user_id, created_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
