DECLARE
    v_table_exists NUMBER := 0;
    v_index_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_table_exists
      FROM user_tables
     WHERE table_name = 'MEDIA_ASSETS';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE media_assets (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                owner_user_id NUMBER(19) NOT NULL,
                domain VARCHAR2(32) NOT NULL,
                status VARCHAR2(32) NOT NULL,
                original_file_name VARCHAR2(512),
                declared_content_type VARCHAR2(128) NOT NULL,
                declared_bytes NUMBER(19) NOT NULL,
                declared_width NUMBER(10) NOT NULL,
                declared_height NUMBER(10) NOT NULL,
                staging_object_key VARCHAR2(2048) NOT NULL,
                object_key VARCHAR2(2048),
                stored_content_type VARCHAR2(128),
                stored_bytes NUMBER(19),
                stored_width NUMBER(10),
                stored_height NUMBER(10),
                upload_expires_at TIMESTAMP(6) NOT NULL,
                finalized_at TIMESTAMP(6),
                derived_from_asset_id NUMBER(19),
                created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT pk_media_assets PRIMARY KEY (id),
                CONSTRAINT fk_media_assets_derived FOREIGN KEY (derived_from_asset_id)
                    REFERENCES media_assets (id)
            )';
    END IF;

    SELECT COUNT(*)
      INTO v_table_exists
      FROM user_tables
     WHERE table_name = 'MEDIA_ASSET_LINKS';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE media_asset_links (
                asset_id NUMBER(19) NOT NULL,
                domain VARCHAR2(32) NOT NULL,
                entity_id NUMBER(19) NOT NULL,
                role VARCHAR2(32) NOT NULL,
                linked_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT pk_media_asset_links PRIMARY KEY (asset_id),
                CONSTRAINT fk_media_asset_links_asset FOREIGN KEY (asset_id)
                    REFERENCES media_assets (id) ON DELETE CASCADE
            )';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'UK_MEDIA_ASSETS_OBJECT_KEY';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uk_media_assets_object_key ON media_assets (object_key)';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'UK_MEDIA_ASSETS_DERIVED';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uk_media_assets_derived ON media_assets (derived_from_asset_id)';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'IDX_MEDIA_ASSETS_OWNER_CREATED';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_media_assets_owner_created ON media_assets (owner_user_id, created_at)';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'IDX_MEDIA_ASSETS_STATUS_EXP';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_media_assets_status_exp ON media_assets (status, upload_expires_at)';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'IDX_MEDIA_ASSETS_DOMAIN_STATUS';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_media_assets_domain_status ON media_assets (domain, status)';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'IDX_MEDIA_LINKS_ENTITY';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_media_links_entity ON media_asset_links (domain, entity_id)';
    END IF;
END;
/
