DECLARE
    v_table_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_table_count
      FROM user_tables
     WHERE table_name = 'DM_ROOMS';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE dm_rooms (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                participant_one_id NUMBER NOT NULL,
                participant_two_id NUMBER NOT NULL,
                created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT chk_dm_rooms_participant_order CHECK (participant_one_id < participant_two_id),
                CONSTRAINT uk_dm_rooms_participants UNIQUE (participant_one_id, participant_two_id),
                CONSTRAINT fk_dm_rooms_participant_one FOREIGN KEY (participant_one_id) REFERENCES users(id) ON DELETE CASCADE,
                CONSTRAINT fk_dm_rooms_participant_two FOREIGN KEY (participant_two_id) REFERENCES users(id) ON DELETE CASCADE
            )
        ]';
    END IF;

    SELECT COUNT(*)
      INTO v_table_count
      FROM user_tables
     WHERE table_name = 'DM_MESSAGES';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE dm_messages (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                room_id NUMBER NOT NULL,
                sender_id NUMBER NOT NULL,
                content VARCHAR2(1000 CHAR) NOT NULL,
                client_message_id VARCHAR2(64 CHAR),
                created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT uk_dm_messages_room_sender_client UNIQUE (room_id, sender_id, client_message_id),
                CONSTRAINT fk_dm_messages_room FOREIGN KEY (room_id) REFERENCES dm_rooms(id) ON DELETE CASCADE,
                CONSTRAINT fk_dm_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE
            )
        ]';
    END IF;
END;
/

DECLARE
    e_index_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_index_exists, -955);
BEGIN
    BEGIN
        EXECUTE IMMEDIATE q'[
            CREATE INDEX idx_dm_messages_room_created_at
                ON dm_messages (room_id, created_at)
        ]';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;
END;
/
