DECLARE
    v_table_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_table_count
      FROM user_tables
     WHERE table_name = 'ADMIN_NON_CANONICAL_CLEANUP_TRACKERS';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            CREATE TABLE admin_non_canonical_cleanup_trackers (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                start_date DATE NOT NULL,
                end_date DATE NOT NULL,
                ticket_url VARCHAR2(500 CHAR),
                assignee VARCHAR2(120 CHAR),
                status VARCHAR2(32 CHAR) NOT NULL,
                note_text CLOB,
                updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                updated_by_admin_id NUMBER(19),
                game_ids_json CLOB DEFAULT '[]' NOT NULL,
                CONSTRAINT uk_admin_non_canonical_cleanup_tracker_range UNIQUE (start_date, end_date)
            )
        ~';
    END IF;
END;
/

DECLARE
    e_index_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_index_exists, -955);
BEGIN
    BEGIN
        EXECUTE IMMEDIATE q'~
            CREATE INDEX idx_admin_non_canonical_cleanup_trackers_updated_at
                ON admin_non_canonical_cleanup_trackers (updated_at)
        ~';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;
END;
/
