-- V142: Rename client_error_feedback.comment → feedback_comment
-- Oracle 23.26 treats COMMENT as a reserved word (ORA-03050), causing scheduled
-- cleanup queries generated by Hibernate to fail at 03:15 KST daily.
-- This rename avoids the reserved-word collision without changing any data.

ALTER TABLE client_error_feedback RENAME COLUMN comment TO feedback_comment;
