-- V142: Rename client_error_feedback.comment → feedback_comment
-- Oracle 23.26 treats COMMENT as a reserved word (ORA-03050), causing scheduled
-- cleanup queries generated by Hibernate to fail at 03:15 KST daily.
-- This rename avoids the reserved-word collision without changing any data.
--
-- Keep migration idempotent: if another environment was pre-fixed or partially
-- migrated by hand, skip renaming when the destination already exists.

DECLARE
    v_has_comment NUMBER;
    v_has_feedback_comment NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_has_comment
      FROM user_tab_columns
     WHERE table_name = 'CLIENT_ERROR_FEEDBACK'
       AND UPPER(column_name) = 'COMMENT';

    SELECT COUNT(*)
      INTO v_has_feedback_comment
      FROM user_tab_columns
     WHERE table_name = 'CLIENT_ERROR_FEEDBACK'
       AND UPPER(column_name) = 'FEEDBACK_COMMENT';

    IF v_has_comment > 0 AND v_has_feedback_comment = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE client_error_feedback RENAME COLUMN "COMMENT" TO feedback_comment';
    END IF;
END;
/
