-- V146: Create daily mate search term aggregate table (Oracle)

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'MATE_SEARCH_TERMS_DAILY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE mate_search_terms_daily (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                search_date DATE NOT NULL,
                normalized_term VARCHAR2(50 CHAR) NOT NULL,
                display_term VARCHAR2(50 CHAR) NOT NULL,
                search_count NUMBER(19) DEFAULT 1 NOT NULL,
                last_searched_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE UNIQUE INDEX uq_mate_search_daily_date_term
            ON mate_search_terms_daily(search_date, normalized_term)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX idx_mate_search_daily_rank
            ON mate_search_terms_daily(search_date, search_count, last_searched_at)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
