DECLARE
    v_table_exists NUMBER := 0;
    v_index_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_table_exists
      FROM user_tables
     WHERE table_name = 'USER_PARTY_FAVORITES';

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE user_party_favorites (
                id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                user_id NUMBER(19) NOT NULL,
                party_id NUMBER(19) NOT NULL,
                created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT pk_user_party_favorites PRIMARY KEY (id),
                CONSTRAINT uq_user_party_favorites UNIQUE (user_id, party_id)
            )';
    END IF;

    SELECT COUNT(*)
      INTO v_index_exists
      FROM user_indexes
     WHERE index_name = 'IDX_UPF_USER_ID';

    IF v_index_exists = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_upf_user_id ON user_party_favorites (user_id)';
    END IF;
END;
/
