-- Persist immutable Mate refund intent and seller payout recovery debt (Oracle).

DECLARE
    v_table_count NUMBER;
    v_column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count
      FROM user_tables
     WHERE table_name = 'PAYMENT_TRANSACTIONS';

    IF v_table_count > 0 THEN
        SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
         WHERE table_name = 'PAYMENT_TRANSACTIONS' AND column_name = 'REQUESTED_REFUND_AMOUNT';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE payment_transactions ADD (requested_refund_amount NUMBER(10))';
        END IF;

        SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
         WHERE table_name = 'PAYMENT_TRANSACTIONS' AND column_name = 'REQUESTED_FEE_AMOUNT';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE payment_transactions ADD (requested_fee_amount NUMBER(10))';
        END IF;

        SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
         WHERE table_name = 'PAYMENT_TRANSACTIONS' AND column_name = 'CANCELLATION_REQUESTED_AT';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE payment_transactions ADD (cancellation_requested_at TIMESTAMP(6) WITH TIME ZONE)';
        END IF;

        SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
         WHERE table_name = 'PAYMENT_TRANSACTIONS' AND column_name = 'PROVIDER_RECONCILED_AT';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE payment_transactions ADD (provider_reconciled_at TIMESTAMP(6) WITH TIME ZONE)';
        END IF;
    END IF;

    SELECT COUNT(*) INTO v_table_count
      FROM user_tables
     WHERE table_name = 'PAYOUT_TRANSACTIONS';

    IF v_table_count > 0 THEN
        SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
         WHERE table_name = 'PAYOUT_TRANSACTIONS' AND column_name = 'RECOVERY_OFFSET_AMOUNT';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE payout_transactions ADD (recovery_offset_amount NUMBER(10) DEFAULT 0 NOT NULL)';
        END IF;

        SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
         WHERE table_name = 'PAYOUT_TRANSACTIONS' AND column_name = 'RECOVERY_OFFSET_RESERVED_AT';
        IF v_column_count = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE payout_transactions ADD (recovery_offset_reserved_at TIMESTAMP(6) WITH TIME ZONE)';
        END IF;
    END IF;
END;
/

DECLARE
    v_table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count
      FROM user_tables
     WHERE table_name = 'SELLER_PAYOUT_RECOVERIES';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE seller_payout_recoveries (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                source_payment_transaction_id NUMBER NOT NULL,
                payout_transaction_id NUMBER,
                seller_user_id NUMBER NOT NULL,
                original_paid_amount NUMBER(10) NOT NULL,
                target_net_amount NUMBER(10) NOT NULL,
                recovery_amount NUMBER(10) NOT NULL,
                recovered_amount NUMBER(10) DEFAULT 0 NOT NULL,
                status VARCHAR2(30) NOT NULL,
                created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
        ]';
    END IF;
END;
/

DECLARE
    v_index_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'UQ_PAYOUT_PAYMENT_TX';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_payout_payment_tx ON payout_transactions(payment_transaction_id)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'UQ_SPR_SOURCE_PAYMENT';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_spr_source_payment ON seller_payout_recoveries(source_payment_transaction_id)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'IDX_SPR_SELLER_STATUS';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_spr_seller_status ON seller_payout_recoveries(seller_user_id, status, id)';
    END IF;
END;
/
