-- Add auditable recovery-offset reservations and quarantine unverified legacy payout completions.

DECLARE
    v_duplicate_count NUMBER;
    v_unverified_count NUMBER;
    v_legacy_offset_count NUMBER;
    v_active_payout_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_duplicate_count
      FROM (
            SELECT payment_transaction_id
              FROM payout_transactions
             GROUP BY payment_transaction_id
            HAVING COUNT(*) > 1
      );
    IF v_duplicate_count > 0 THEN
        raise_application_error(-20001, 'MATE_PAYOUT_DUPLICATES_REQUIRE_MANUAL_RECONCILIATION');
    END IF;

    SELECT COUNT(*) INTO v_unverified_count
      FROM payout_transactions payout
     WHERE payout.status = 'COMPLETED'
       AND NVL(payout.failure_code, '-') <> 'PAYOUT_COMPLETION_VERIFIED';
    IF v_unverified_count > 0 THEN
        raise_application_error(-20002, 'MATE_LEGACY_PAYOUT_COMPLETION_REQUIRES_MANUAL_RECONCILIATION');
    END IF;

    SELECT COUNT(*) INTO v_legacy_offset_count
      FROM payout_transactions
     WHERE NVL(recovery_offset_amount, 0) <> 0;
    IF v_legacy_offset_count > 0 THEN
        raise_application_error(-20003, 'MATE_LEGACY_RECOVERY_OFFSET_REQUIRES_MANUAL_RECONCILIATION');
    END IF;

    SELECT COUNT(*) INTO v_active_payout_count
     FROM payout_transactions
     WHERE status = 'REQUESTED'
        OR (status = 'FAILED' AND next_retry_at IS NOT NULL)
        OR (status = 'FAILED' AND failure_code IN (
            'TOSS_PAYOUT_REQUEST_FAILED',
            'TOSS_PAYOUT_EMPTY_RESPONSE',
            'TOSS_PAYOUT_NO_PROVIDER_REF',
            'PAYOUT_MANUAL_RECONCILIATION_REQUIRED'
        ));
    IF v_active_payout_count > 0 THEN
        raise_application_error(-20004, 'MATE_ACTIVE_PAYOUT_REQUIRES_MANUAL_RECONCILIATION');
    END IF;
END;
/

DECLARE
    v_column_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
     WHERE table_name = 'PAYOUT_TRANSACTIONS' AND column_name = 'PROVIDER_CODE';
    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE payout_transactions ADD (provider_code VARCHAR2(30))';
    END IF;

    SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
     WHERE table_name = 'PAYOUT_TRANSACTIONS' AND column_name = 'PROVIDER_SELLER_ID';
    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE payout_transactions ADD (provider_seller_id VARCHAR2(200))';
    END IF;

    SELECT COUNT(*) INTO v_column_count FROM user_tab_columns
     WHERE table_name = 'PAYOUT_TRANSACTIONS' AND column_name = 'CLAIM_PROTOCOL';
    IF v_column_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE payout_transactions ADD (claim_protocol VARCHAR2(30))';
    END IF;
END;
/

DECLARE
    v_constraint_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_constraint_count FROM user_constraints
     WHERE constraint_name = 'CK_PAYOUT_OFFSET_PROTOCOL';
    IF v_constraint_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE payout_transactions
            ADD CONSTRAINT ck_payout_offset_protocol
            CHECK (NVL(recovery_offset_amount, 0) = 0 OR NVL(claim_protocol, '-') = 'SNAPSHOT_V1')
        ]';
    END IF;

    SELECT COUNT(*) INTO v_constraint_count FROM user_constraints
     WHERE constraint_name = 'CK_PAYOUT_REQUESTED_PROTOCOL';
    IF v_constraint_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE payout_transactions
            ADD CONSTRAINT ck_payout_requested_protocol
            CHECK (status <> 'REQUESTED' OR NVL(claim_protocol, '-') = 'SNAPSHOT_V1')
        ]';
    END IF;

    SELECT COUNT(*) INTO v_constraint_count FROM user_constraints
     WHERE constraint_name = 'CK_PAYOUT_COMPLETION_VERIFIED';
    IF v_constraint_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE payout_transactions
            ADD CONSTRAINT ck_payout_completion_verified
            CHECK (status <> 'COMPLETED' OR NVL(failure_code, '-') = 'PAYOUT_COMPLETION_VERIFIED')
        ]';
    END IF;
END;
/

DECLARE
    v_table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count
      FROM user_tables
     WHERE table_name = 'SELLER_RECOVERY_OFFSET_ALLOCATIONS';
    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE seller_recovery_offset_allocations (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                payout_transaction_id NUMBER NOT NULL,
                recovery_id NUMBER NOT NULL,
                amount NUMBER(10) NOT NULL,
                status VARCHAR2(30) NOT NULL,
                created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
                updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
            )
        ]';
    END IF;
END;
/

DECLARE
    v_index_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'UQ_SROA_PAYOUT_RECOVERY';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_sroa_payout_recovery ON seller_recovery_offset_allocations(payout_transaction_id, recovery_id)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'IDX_SROA_RECOVERY_STATUS';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_sroa_recovery_status ON seller_recovery_offset_allocations(recovery_id, status)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'IDX_SROA_PAYOUT_STATUS';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_sroa_payout_status ON seller_recovery_offset_allocations(payout_transaction_id, status, id)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'IDX_PAYOUT_STATUS_NEXT_RETRY';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_payout_status_next_retry ON payout_transactions(status, next_retry_at, id)';
    END IF;
END;
/

MERGE INTO seller_payout_recoveries recovery
USING (
    SELECT
        payment.id AS source_payment_transaction_id,
        payout.id AS payout_transaction_id,
        payment.seller_user_id,
        GREATEST(
            NVL(payout.requested_amount, 0)
                + NVL(payout.recovery_offset_amount, 0),
            0) AS original_paid_amount,
        GREATEST(NVL(payment.net_amount, 0), 0) AS target_net_amount,
        GREATEST(
            NVL(payout.requested_amount, 0)
                + NVL(payout.recovery_offset_amount, 0)
                - NVL(payment.net_amount, 0),
            0) AS recovery_amount
      FROM payment_transactions payment
      JOIN payout_transactions payout
        ON payout.payment_transaction_id = payment.id
       AND payout.status = 'COMPLETED'
       AND payout.failure_code = 'PAYOUT_COMPLETION_VERIFIED'
     WHERE payment.settlement_status = 'REFUNDED_AFTER_SETTLEMENT'
) source
ON (recovery.source_payment_transaction_id = source.source_payment_transaction_id)
WHEN NOT MATCHED THEN
    INSERT (
        source_payment_transaction_id,
        payout_transaction_id,
        seller_user_id,
        original_paid_amount,
        target_net_amount,
        recovery_amount,
        recovered_amount,
        status,
        created_at,
        updated_at
    )
    VALUES (
        source.source_payment_transaction_id,
        source.payout_transaction_id,
        source.seller_user_id,
        source.original_paid_amount,
        source.target_net_amount,
        source.recovery_amount,
        0,
        CASE WHEN source.recovery_amount > 0 THEN 'PENDING' ELSE 'RECOVERED' END,
        SYSTIMESTAMP,
        SYSTIMESTAMP
    );
