DECLARE
    v_table_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_table_count
      FROM user_tables
     WHERE table_name = 'REALTIME_OUTBOX_EVENTS';

    IF v_table_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE realtime_outbox_events (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                envelope_version NUMBER(10) NOT NULL,
                event_id VARCHAR2(128) NOT NULL,
                target VARCHAR2(20) NOT NULL,
                destination VARCHAR2(255) NOT NULL,
                user_id VARCHAR2(128),
                payload CLOB NOT NULL,
                status VARCHAR2(20) NOT NULL,
                attempt_count NUMBER(10) DEFAULT 0 NOT NULL,
                available_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                locked_by VARCHAR2(128),
                locked_until TIMESTAMP(6) WITH TIME ZONE,
                last_error VARCHAR2(1000 CHAR),
                created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
                published_at TIMESTAMP(6) WITH TIME ZONE
            )
        ]';
    END IF;
END;
/

DECLARE
    v_index_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'UQ_RT_OUTBOX_EVENT';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_rt_outbox_event ON realtime_outbox_events(event_id)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'IDX_RT_OUTBOX_DUE';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_rt_outbox_due ON realtime_outbox_events(status, available_at, id)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'IDX_RT_OUTBOX_LEASE';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_rt_outbox_lease ON realtime_outbox_events(status, locked_until, id)';
    END IF;

    SELECT COUNT(*) INTO v_index_count FROM user_indexes
     WHERE index_name = 'IDX_RT_OUTBOX_CLEANUP';
    IF v_index_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_rt_outbox_cleanup ON realtime_outbox_events(status, published_at, id)';
    END IF;
END;
/
