-- Force re-login while replacing persisted bearer tokens with HMAC digests only.
DELETE FROM refresh_tokens;
COMMIT;

ALTER TABLE refresh_tokens ADD (token_digest VARCHAR2(64 CHAR) NOT NULL);
ALTER TABLE refresh_tokens DROP COLUMN token;
CREATE UNIQUE INDEX uk_refresh_tokens_token_digest ON refresh_tokens(token_digest);

CREATE TABLE oauth_email_challenges (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    challenge_id VARCHAR2(36 CHAR) NOT NULL,
    token_digest VARCHAR2(64 CHAR),
    provider VARCHAR2(20 CHAR) NOT NULL,
    provider_id VARCHAR2(255 CHAR) NOT NULL,
    email VARCHAR2(320 CHAR),
    name VARCHAR2(255 CHAR),
    profile_image_url VARCHAR2(2048 CHAR),
    created_at TIMESTAMP NOT NULL,
    expiry_date TIMESTAMP,
    status VARCHAR2(20 CHAR) NOT NULL,
    used NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX uk_oauth_email_chal_digest
    ON oauth_email_challenges(token_digest);
CREATE UNIQUE INDEX uk_oauth_email_chal_id
    ON oauth_email_challenges(challenge_id);
CREATE INDEX ix_oauth_email_chal_provider
    ON oauth_email_challenges(provider, provider_id);
