-- V30: Manage user_providers table and columns safely
-- Handles missing table and missing email column scenarios idempotently

DECLARE
    v_count NUMBER;
BEGIN
    -- 1. Check if table exits
    SELECT count(*) INTO v_count FROM user_tables WHERE table_name = 'USER_PROVIDERS';
    
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE TABLE user_providers (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            provider VARCHAR2(20) NOT NULL,
            providerid VARCHAR2(255) NOT NULL,
            connected_at TIMESTAMP,
            CONSTRAINT uk_user_provider_pid UNIQUE (provider, providerid),
            CONSTRAINT uk_user_provider_uid UNIQUE (user_id, provider),
            CONSTRAINT fk_user_providers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )';
        EXECUTE IMMEDIATE 'CREATE INDEX idx_user_providers_user ON user_providers(user_id)';
    END IF;

    -- 2. Check if email column exists
    SELECT count(*) INTO v_count FROM user_tab_columns WHERE table_name = 'USER_PROVIDERS' AND column_name = 'EMAIL';
    
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE user_providers ADD email VARCHAR2(255)';
    END IF;
END;
/
