-- V56: Create payment_intents table for Toss payment intent tracking (Oracle)

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955); -- ORA-00955
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE payment_intents (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            order_id VARCHAR2(100) NOT NULL,
            party_id NUMBER NOT NULL,
            applicant_id NUMBER NOT NULL,
            expected_amount NUMBER(10) NOT NULL,
            currency VARCHAR2(10) DEFAULT 'KRW' NOT NULL,
            payment_type VARCHAR2(20) NOT NULL,
            pay_mode VARCHAR2(20) NOT NULL,
            status VARCHAR2(30) NOT NULL,
            payment_key VARCHAR2(200),
            failure_code VARCHAR2(100),
            failure_message VARCHAR2(1000),
            expires_at TIMESTAMP(6) WITH TIME ZONE,
            confirmed_at TIMESTAMP(6) WITH TIME ZONE,
            canceled_at TIMESTAMP(6) WITH TIME ZONE,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]';
EXCEPTION
    WHEN e_table_exists THEN
        NULL;
END;
/

DECLARE
    e_index_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_index_exists, -955); -- ORA-00955
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_payment_intents_order_id ON payment_intents(order_id)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_payment_intents_party_applicant ON payment_intents(party_id, applicant_id)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_payment_intents_status_expires ON payment_intents(status, expires_at)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_payment_intents_payment_key ON payment_intents(payment_key)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;
END;
/
