-- V57: Create payment_transactions and payout_transactions tables (Oracle)

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955); -- ORA-00955
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE payment_transactions (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            party_id NUMBER NOT NULL,
            application_id NUMBER NOT NULL,
            buyer_user_id NUMBER NOT NULL,
            seller_user_id NUMBER NOT NULL,
            flow_type VARCHAR2(30) NOT NULL,
            order_id VARCHAR2(100) NOT NULL,
            payment_key VARCHAR2(200) NOT NULL,
            gross_amount NUMBER(10) NOT NULL,
            fee_amount NUMBER(10) DEFAULT 0 NOT NULL,
            refund_amount NUMBER(10) DEFAULT 0 NOT NULL,
            net_amount NUMBER(10) NOT NULL,
            payment_status VARCHAR2(30) NOT NULL,
            settlement_status VARCHAR2(30) NOT NULL,
            cancel_reason_type VARCHAR2(30),
            cancel_memo VARCHAR2(1000),
            refund_policy_applied VARCHAR2(100),
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]';
EXCEPTION
    WHEN e_table_exists THEN
        NULL;
END;
/

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955); -- ORA-00955
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE payout_transactions (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            payment_transaction_id NUMBER NOT NULL,
            seller_id NUMBER NOT NULL,
            requested_amount NUMBER(10) NOT NULL,
            status VARCHAR2(30) NOT NULL,
            provider_ref VARCHAR2(200),
            requested_at TIMESTAMP(6) WITH TIME ZONE,
            completed_at TIMESTAMP(6) WITH TIME ZONE,
            fail_reason VARCHAR2(1000),
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]';
EXCEPTION
    WHEN e_table_exists THEN
        NULL;
END;
/

DECLARE
    e_index_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_index_exists, -955); -- ORA-00955
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_payment_transactions_order_id ON payment_transactions(order_id)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_payment_transactions_payment_key ON payment_transactions(payment_key)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_payment_transactions_application_id ON payment_transactions(application_id)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_payment_transactions_status ON payment_transactions(payment_status, settlement_status)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_payout_transactions_payment_id ON payout_transactions(payment_transaction_id)';
    EXCEPTION
        WHEN e_index_exists THEN NULL;
    END;
END;
/
