-- V69: Create awards table for production runtime entities

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'AWARDS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE awards (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                award_type VARCHAR2(100) NOT NULL,
                player_name VARCHAR2(100) NOT NULL,
                award_year NUMBER(10) NOT NULL,
                position VARCHAR2(50)
            )';
    END IF;
END;
/
