-- V86: Create mate_seller_payout_profiles table (Oracle)

DECLARE
    e_table_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_table_exists, -955); -- ORA-00955
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE mate_seller_payout_profiles (
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            user_id NUMBER NOT NULL,
            provider VARCHAR2(20) NOT NULL,
            provider_seller_id VARCHAR2(120) NOT NULL,
            kyc_status VARCHAR2(50),
            metadata_json CLOB,
            created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
            updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
        )
    ]';
EXCEPTION
    WHEN e_table_exists THEN
        NULL;
END;
/

DECLARE
    e_index_exists EXCEPTION;
    PRAGMA EXCEPTION_INIT(e_index_exists, -955); -- ORA-00955
BEGIN
    BEGIN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_mate_seller_payout_profiles_user_provider ON mate_seller_payout_profiles(user_id, provider)';
    EXCEPTION
        WHEN e_index_exists THEN
            NULL;
    END;

    BEGIN
        EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX uq_mate_seller_payout_profiles_provider_seller ON mate_seller_payout_profiles(provider, provider_seller_id)';
    EXCEPTION
        WHEN e_index_exists THEN
            NULL;
    END;
END;
/

