-- ============================================
-- V8: Create Leaderboard System Tables
-- ============================================
-- Gamified prediction leaderboard with scoring, streaks, levels, and power-ups

-- User Score Tracking
CREATE TABLE user_scores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    total_score NUMBER DEFAULT 0,
    season_score NUMBER DEFAULT 0,
    monthly_score NUMBER DEFAULT 0,
    weekly_score NUMBER DEFAULT 0,
    current_streak NUMBER DEFAULT 0,
    max_streak NUMBER DEFAULT 0,
    user_level NUMBER DEFAULT 1,
    experience_points NUMBER DEFAULT 0,
    correct_predictions NUMBER DEFAULT 0,
    total_predictions NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_scores_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_scores_user UNIQUE (user_id)
);

-- Score Event Log (history of scoring events)
CREATE TABLE score_events (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    prediction_id NUMBER,
    game_id VARCHAR2(50),
    event_type VARCHAR2(50) NOT NULL,
    base_score NUMBER NOT NULL,
    multiplier NUMBER(5,2) DEFAULT 1.0,
    final_score NUMBER NOT NULL,
    streak_count NUMBER DEFAULT 0,
    description VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_score_events_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- User Power-up Inventory
CREATE TABLE user_powerups (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    powerup_type VARCHAR2(50) NOT NULL,
    quantity NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_powerups_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_powerups UNIQUE (user_id, powerup_type),
    CONSTRAINT chk_powerup_type CHECK (powerup_type IN ('MAGIC_BAT', 'GOLDEN_GLOVE', 'SCOUTER'))
);

-- Active Power-up Effects
CREATE TABLE active_powerups (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    powerup_type VARCHAR2(50) NOT NULL,
    game_id VARCHAR2(50),
    activated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    used NUMBER(1) DEFAULT 0,
    CONSTRAINT fk_active_powerups_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_active_powerup_type CHECK (powerup_type IN ('MAGIC_BAT', 'GOLDEN_GLOVE', 'SCOUTER'))
);

-- Achievements/Badges Definition
CREATE TABLE achievements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(50) NOT NULL,
    name_ko VARCHAR2(100) NOT NULL,
    name_en VARCHAR2(100),
    description_ko VARCHAR2(500),
    description_en VARCHAR2(500),
    icon_url VARCHAR2(500),
    rarity VARCHAR2(20) DEFAULT 'COMMON',
    points_required NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_achievements_code UNIQUE (code),
    CONSTRAINT chk_rarity CHECK (rarity IN ('COMMON', 'RARE', 'EPIC', 'LEGENDARY'))
);

-- User Achievements (junction table)
CREATE TABLE user_achievements (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    achievement_id NUMBER NOT NULL,
    earned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_achievements_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_achievements_achievement FOREIGN KEY (achievement_id) REFERENCES achievements(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_achievements UNIQUE (user_id, achievement_id)
);

-- Leaderboard Snapshots (for historical rankings)
CREATE TABLE leaderboard_snapshots (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    snapshot_type VARCHAR2(20) NOT NULL,
    snapshot_date DATE NOT NULL,
    rank_position NUMBER NOT NULL,
    score NUMBER NOT NULL,
    user_level NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_leaderboard_snapshots_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_snapshot_type CHECK (snapshot_type IN ('DAILY', 'WEEKLY', 'MONTHLY', 'SEASON'))
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

-- User scores indexes
CREATE INDEX idx_user_scores_total ON user_scores(total_score DESC);
CREATE INDEX idx_user_scores_season ON user_scores(season_score DESC);
CREATE INDEX idx_user_scores_monthly ON user_scores(monthly_score DESC);
CREATE INDEX idx_user_scores_weekly ON user_scores(weekly_score DESC);
CREATE INDEX idx_user_scores_level ON user_scores(user_level DESC);
CREATE INDEX idx_user_scores_streak ON user_scores(current_streak DESC);

-- Score events indexes
CREATE INDEX idx_score_events_user ON score_events(user_id);
CREATE INDEX idx_score_events_created ON score_events(created_at DESC);
CREATE INDEX idx_score_events_user_created ON score_events(user_id, created_at DESC);

-- Active powerups indexes
CREATE INDEX idx_active_powerups_user ON active_powerups(user_id);
CREATE INDEX idx_active_powerups_expires ON active_powerups(expires_at);

-- Leaderboard snapshots indexes
CREATE INDEX idx_leaderboard_snapshots_type_date ON leaderboard_snapshots(snapshot_type, snapshot_date DESC);
CREATE INDEX idx_leaderboard_snapshots_rank ON leaderboard_snapshots(snapshot_type, snapshot_date, rank_position);

-- ============================================
-- INSERT DEFAULT ACHIEVEMENTS
-- ============================================

INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('FIRST_PREDICTION', '첫 예측', 'First Prediction', '첫 번째 승부 예측 완료', 'COMMON', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('STREAK_3', '3연승', '3 Streak', '3연승 달성', 'COMMON', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('STREAK_5', '5연승', '5 Streak', '5연승 달성', 'RARE', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('STREAK_7', '7연승', '7 Streak', '7연승 달성! 불타는 예측왕!', 'EPIC', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('STREAK_10', '10연승', '10 Streak', '전설의 10연승 달성!', 'LEGENDARY', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('PERFECT_DAY', '퍼펙트 데이', 'Perfect Day', '하루 모든 경기 예측 성공', 'EPIC', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('UPSET_MASTER', '이변 예측왕', 'Upset Master', '이변 예측 5회 성공', 'RARE', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('LEVEL_10', '루키 탈출', 'Rookie Graduate', '레벨 10 달성', 'COMMON', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('LEVEL_30', '마이너리거', 'Minor Leaguer', '레벨 30 달성', 'RARE', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('LEVEL_60', '메이저리거', 'Major Leaguer', '레벨 60 달성', 'EPIC', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('HALL_OF_FAME', '명예의 전당', 'Hall of Fame', '레벨 99 달성', 'LEGENDARY', 0);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('SCORE_100K', '10만 점', '100K Points', '총 점수 100,000점 달성', 'RARE', 100000);
INSERT INTO achievements (code, name_ko, name_en, description_ko, rarity, points_required) VALUES
('SCORE_1M', '100만 점', '1M Points', '총 점수 1,000,000점 달성', 'LEGENDARY', 1000000);

COMMIT;
