-- V94: Create user_policy_consents table for required policy version tracking (Oracle)

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'USER_POLICY_CONSENTS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE TABLE user_policy_consents (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                policy_type VARCHAR2(40 CHAR) NOT NULL,
                policy_version VARCHAR2(20 CHAR) NOT NULL,
                consented_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
                consent_method VARCHAR2(20 CHAR) NOT NULL,
                consent_ip VARCHAR2(64 CHAR),
                consent_user_agent CLOB
            )';
    END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE user_policy_consents
            ADD CONSTRAINT fk_user_policy_consents_user
            FOREIGN KEY (user_id) REFERENCES users(id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'ALTER TABLE user_policy_consents
            ADD CONSTRAINT uq_user_policy_consents_user_policy_version
            UNIQUE (user_id, policy_type, policy_version)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2261 AND SQLCODE != -2264 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE
        'CREATE INDEX ix_user_policy_consents_user_id ON user_policy_consents(user_id)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

